//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adres()
        {
            this.Kullanici = new HashSet<Kullanici>();
            this.YayinEvi = new HashSet<YayinEvi>();
        }
    
        public int adresNo { get; set; }
        public string cadde { get; set; }
        public string sokak { get; set; }
        public string mahalle { get; set; }
        public string bina { get; set; }
        public Nullable<int> binaNo { get; set; }
        public Nullable<int> daireNo { get; set; }
        public string ilce { get; set; }
        public string il { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YayinEvi> YayinEvi { get; set; }
    }
}
