//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public long tcNo { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string telefonNo { get; set; }
        public Nullable<int> adres { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
    
        public virtual Adres Adres1 { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
