//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odunc
    {
        public long oduncNo { get; set; }
        public long uye { get; set; }
        public long kitap { get; set; }
        public Nullable<System.DateTime> oduncTarihi { get; set; }
        public Nullable<System.DateTime> teslimTarihi { get; set; }
        public string onay { get; set; }
    
        public virtual Kitap Kitap1 { get; set; }
        public virtual Uye Uye1 { get; set; }
    }
}
