//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public long tcNo { get; set; }
        public int sicilNo { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
